'use client';
import { Check } from 'lucide-react';
import {
  type ComponentProps,
  createContext,
  type HTMLAttributes,
  type ReactNode,
  type RefObject,
  use,
  useMemo,
  useRef,
} from 'react';
import { cn } from '@/utils/cn';
import { useCopyButton } from '@/utils/use-copy-button';
import { buttonVariants } from '@/components/ui/button';
import { useTranslations } from '@/contexts/translations';
import {
  Tabs,
  TabsContent,
  TabsIndicator,
  TabsList,
  TabsTrigger,
} from '@/components/ui/tabs';
import { mergeRefs } from '@/utils/merge-refs';

export interface CodeBlockProps extends ComponentProps<'figure'> {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  viewportProps?: HTMLAttributes<HTMLElement>;

  /**
   * show line numbers
   */
  'data-line-numbers'?: boolean;

  /**
   * @defaultValue 1
   */
  'data-line-numbers-start'?: number;

  Actions?: (props: { className?: string; children?: ReactNode }) => ReactNode;
}

const TabsContext = createContext<{
  containerRef: RefObject<HTMLDivElement | null>;
  nested: boolean;
} | null>(null);

export function Pre(props: ComponentProps<'pre'>) {
  return (
    <pre {...props} className={cn('min-w-full w-max *:flex *:flex-col', props.className)}>
      {props.children}
    </pre>
  );
}

interface CodeBlockShellProps extends CodeBlockProps {
  actionsPlacement?: 'header' | 'overlay';
}

function CodeBlockShell({
  ref,
  title,
  allowCopy = true,
  keepBackground = false,
  icon,
  viewportProps = {},
  children,
  Actions = (props) => <div {...props} className={cn('empty:hidden', props.className)} />,
  actionsPlacement = title ? 'header' : 'overlay',
  ...props
}: CodeBlockShellProps) {
  const inTab = use(TabsContext) !== null;
  const areaRef = useRef<HTMLDivElement>(null);
  const actions = allowCopy ? (
    <CopyButton containerRef={areaRef} overlay={actionsPlacement === 'overlay'} />
  ) : null;

  return (
    <figure
      ref={ref}
      dir="ltr"
      {...props}
      tabIndex={-1}
      className={cn(
        'group/codeblock relative border shadow-sm not-prose overflow-hidden text-sm',
        inTab
          ? 'bg-fd-secondary -mx-px -mb-px last:rounded-b-xl'
          : 'my-4 bg-fd-card rounded-xl',
        keepBackground && 'bg-(--shiki-light-bg) dark:bg-(--shiki-dark-bg)',
        'shiki',
        props.className,
      )}
    >
      {title ? (
        <div className="flex h-9.5 items-center gap-2 border-b border-fd-border bg-fd-muted/60 px-4 text-fd-muted-foreground dark:bg-fd-muted/40">
          {typeof icon === 'string' ? (
            <div
              className="[&_svg]:size-3.5"
              dangerouslySetInnerHTML={{
                __html: icon,
              }}
            />
          ) : (
            icon
          )}
          <figcaption className="flex-1 truncate text-xs font-medium">{title}</figcaption>
          {Actions({
            className: '-me-2',
            children: actionsPlacement === 'header' ? actions : null,
          })}
        </div>
      ) : actionsPlacement === 'overlay' ? (
        Actions({
          className: cn(
            'absolute top-2 right-2 z-2 rounded-lg text-fd-muted-foreground',
            'opacity-0 transition-opacity',
            'group-hover/codeblock:opacity-100 group-focus-within/codeblock:opacity-100',
            'pointer-events-none group-hover/codeblock:pointer-events-auto group-focus-within/codeblock:pointer-events-auto',
          ),
          children: actions,
        })
      ) : (
        Actions({
          className: 'hidden',
          children: null,
        })
      )}
      <div
        ref={areaRef}
        {...viewportProps}
        role="region"
        tabIndex={0}
        className={cn(
          'text-[0.8125rem] py-3.5 overflow-auto max-h-[600px] fd-scroll-container focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-fd-ring',
          viewportProps.className,
        )}
        style={
          {
            // space for toolbar
            '--padding-right': !title ? 'calc(var(--spacing) * 8)' : undefined,
            counterSet: props['data-line-numbers']
              ? `line ${Number(props['data-line-numbers-start'] ?? 1) - 1}`
              : undefined,
            ...viewportProps.style,
          } as object
        }
      >
        {children}
      </div>
    </figure>
  );
}

export function HeadlessCodeBlock(props: CodeBlockProps) {
  return <CodeBlockShell {...props} title={undefined} actionsPlacement="overlay" />;
}

export function CodeBlock(props: CodeBlockProps) {
  return <CodeBlockShell {...props} />;
}

function CopyIcon({ className }: { className?: string }) {
  return (
    <svg
      width="36"
      height="36"
      viewBox="0 0 36 36"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden
    >
      <path
        d="M22.95 32.9998H8.25C5.25 32.9998 3 30.7498 3 27.7498V13.0498C3 10.1998 5.25 7.7998 8.25 7.7998H22.95C25.8 7.7998 28.2 10.0498 28.2 13.0498V27.7498C28.05 30.7498 25.8 32.9998 22.95 32.9998ZM8.25 10.9498C7.05 10.9498 6 11.8498 6 13.0498V27.7498C6 28.9498 7.05 29.9998 8.25 29.9998H22.95C24.15 29.9998 25.2 28.9498 25.2 27.7498V13.0498C25.2 11.8498 24.15 10.7998 22.95 10.7998H8.25V10.9498Z"
        fill="currentColor"
      />
      <path
        d="M31.5004 26.85C30.6004 26.85 30.0004 26.25 30.0004 25.35V9.45C30.0004 7.5 28.5004 6 26.5504 6H10.6504C9.75039 6 9.15039 5.4 9.15039 4.5C9.15039 3.6 9.75039 3 10.6504 3H26.5504C30.1504 3 33.0004 5.85 33.0004 9.45V25.35C33.0004 26.25 32.4004 26.85 31.5004 26.85Z"
        fill="currentColor"
      />
    </svg>
  );
}

function CopyButton({
  className,
  containerRef,
  overlay = false,
  ...props
}: ComponentProps<'button'> & {
  containerRef: RefObject<HTMLElement | null>;
  overlay?: boolean;
}) {
  const t = useTranslations({ note: 'code block' });
  const [checked, onClick] = useCopyButton(() => {
    const pre = containerRef.current?.getElementsByTagName('pre').item(0);
    if (!pre) return;

    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll('.nd-copy-ignore').forEach((node) => {
      node.replaceWith('\n');
    });

    void navigator.clipboard.writeText(clone.textContent ?? '');
  });

  return (
    <button
      type="button"
      data-checked={checked || undefined}
      className={cn(
        buttonVariants({
          className: 'hover:text-fd-accent-foreground data-checked:text-fd-accent-foreground',
          size: 'icon-xs',
        }),
        overlay &&
          'border border-fd-border/80 bg-fd-background/80 shadow-sm backdrop-blur-md hover:bg-fd-background/95',
        className,
      )}
      aria-label={
        checked ? t('Copied Text', { note: 'aria-label' }) : t('Copy Text', { note: 'aria-label' })
      }
      onClick={onClick}
      {...props}
    >
      {checked ? <Check className="size-4" /> : <CopyIcon className="size-4" />}
    </button>
  );
}

export function CodeBlockTabs({ ref, className, ...props }: ComponentProps<typeof Tabs>) {
  const containerRef = useRef<HTMLDivElement>(null);
  const nested = use(TabsContext) !== null;

  return (
    <Tabs
      ref={mergeRefs(containerRef, ref)}
      {...props}
      className={(s) =>
        cn(
          'bg-fd-card rounded-xl border',
          !nested && 'my-4',
          typeof className === 'function' ? className(s) : className,
        )
      }
    >
      <TabsContext
        value={useMemo(
          () => ({
            containerRef,
            nested,
          }),
          [nested],
        )}
      >
        {props.children}
      </TabsContext>
    </Tabs>
  );
}

export function CodeBlockTabsList({
  className,
  children,
  ...props
}: ComponentProps<typeof TabsList>) {
  return (
    <TabsList
      {...props}
      className={(s) =>
        cn(
          'relative flex flex-row px-2 overflow-x-auto text-fd-muted-foreground',
          typeof className === 'function' ? className(s) : className,
        )
      }
    >
      {children}
      <TabsIndicator
        className="absolute bottom-0 left-0 z-0 h-px w-(--active-tab-width) translate-x-(--active-tab-left) bg-fd-primary transition-[translate,width] duration-200 ease-[cubic-bezier(0.23,1,0.32,1)]"
        renderBeforeHydration
      />
    </TabsList>
  );
}

export function CodeBlockTabsTrigger({
  children,
  className,
  ...props
}: ComponentProps<typeof TabsTrigger>) {
  return (
    <TabsTrigger
      {...props}
      className={(s) =>
        cn(
          'relative z-1 group inline-flex text-sm font-medium text-nowrap items-center transition-colors gap-2 px-2 py-1.5 [&_svg]:size-3.5',
          s.active ? 'text-fd-primary' : 'hover:text-fd-accent-foreground',
          typeof className === 'function' ? className(s) : className,
        )
      }
    >
      {children}
    </TabsTrigger>
  );
}

export function CodeBlockTab({ className, ...props }: ComponentProps<typeof TabsContent>) {
  return (
    <TabsContent
      {...props}
      className={(s) => cn(typeof className === 'function' ? className(s) : className)}
    />
  );
}
